# Site settings
course_name: ECE60022 Wireless Communication Networks
course_description: "
This course will cover fundamental concepts in mobile wireless systems, such as: 
<ul>
 <li> *channel modeling*, including propagation, fading factors, capacity, and delay;</li>
<li> *cellular systems*, including 2G/3G/4G/5G/NextG network architectures;</li>
<li> *wireless LANs and ad hoc networks*, including unstructured communication among the Internet
of Things (IoT);
<li> *resource allocation*, including power control, channel assignment, scheduling, routing, and
random access protocols, and </li>
<li> *wireless intelligence*, including machine learning considerations in heterogeneous mobile
systems.</li>
</ul>
Besides understanding the methodologies driving emerging and legacy wireless systems, the
course will emphasize the engineering challenges that must be considered for the future of wireless
communications networks."

# The course is composed of four components: (i) Vulnerability Finding, (ii) Automated Patching, (iii) Patch Propagation, and (iv) Vulnerability Prevention.
# <ul>
# <li>Vulnerability Finding: We understand the basics of vulnerability finding techniques: Static analysis
# (Pattern-based/ Dataflow based/ Type-based/DSL based), Dynamic Analysis (Different Flavors of Fuzzing
# and dynamic symbolic execution), Machine Learning, and a combination of all the above.</li>

# <li>Automated Patching: Automated Program repair techniques: Pattern-based/ Dynamic analysis based/ Machine learning etc.</li>

# <li>Patch Propagation: Understanding the problem of propagating patches caused by software diversity
# and potential solutions.</li>

# <li>Vulnerability Prevention: Type-safe languages (Rust, Go, etc.), Retrofitting techniques (Sanitizers: ASAN, etc.),
# Type-safe dialects (Checked C/Cyclone/etc.).</li>
# </ul>

course_prereqs: "
In the past, ECE 60022 has required ECE 547 (Introduction to Computer Communication Networks) as a pre-requisite. For this offering, while some background understanding of
networking (such as in ECE 547) will be helpful, it is not required.
Students are expected to have a basic understanding of probability and digital communications, as
would be obtained from a typical undergraduate EE/ECE program."

learning_objectives: " Students will leave the course with an understanding of the fundamental principles underlying
wireless communications. This understanding will cross several layers of the network protocol
stack, from the physical wireless channels that these communication systems operate over to 
network design, control, and protocol issues. Students will gain familiarity with the state-of-the art
technologies and key challenges that need to be addressed if resource-intensive, latency-sensitive
applications (such as those arising from machine learning) are to be run on wireless channels.
"

# For every component, we will start with basics and cover the state-of-the-art techniques.
# We will also be reading research papers and try to analyze the pros and cons critically."
evaluation: "
The following forms of assessment throughout the semester will determine your grades:
<ul> <li> Homework (25%)</li>
<ul>
<li> There will be 4 graded homework assignments throughout the semester, all equally weighted.
One will be due approximately every 3 weeks.</li>
<li> These assignments will have math-type problems in them. Students are encouraged to write up
their solutions using Latex, though hand-written problem sets will be accepted too.</li>
<li> Homework must be turned in as a hardcopy to the instructor.</li>
</ul>
<li> Exams (35%)</li>
<ul>
<li> There will be two exams throughout the semester, both equally weighted. The first one will be
in mid-February, and the second one will be in early-April. There is no final exam, and neither
of the exams are cumulative.</li> 
<li> The exams will either be in class or take home (to be decided).</li> 
</ul> 
<li> Projects (40%)</li>
<ul>
<li> There will be one assigned “mini-project”, with the topic chosen by the instructor. This will be
10% of the final grade. It will be released towards the end of January, and you will have roughly
one month to work on it.</li> 
<li> Most importantly, there will be a “term project”, which will be on a research topic selected by
the student (and approved by the instructor). This will be 30% of the final grade. Students are
strongly encouraged to tie this project in with their research interests. Project proposals will be
due in early March. The deliverables will be a final report prepared in the format of a 6-page
research paper, and a presentation during the last week of classes.</li> 
</ul> 
</ul> "

# We will use the following distribution for grading:
# <ul>
#   <li>Four assignments (10% each, Total: 40%).</li>
#   <li>Midterm 1 (10%).</li>
#   <li>Midterm 2 (10%).</li>
#   <li>Paper presentation (10%).</li>
#   <li>Course Project (30%).</li>
# </ul>
# This is a project-heavy course with one-third of the grade depends on the successful
# completion of the project.
# "
course_project: "The goal of the course project is to enable students to experience various aspects of
software security research.  The result of the project will be a conference-style presentation.
This is a semester-long project and is recommended to be done in groups of up to three students.
Each project group is expected to decide milestones and will receive grades based on the satisfactory
completion of these milestones and the presentation. Potential project ideas are
<a href=\"https://docs.google.com/spreadsheets/d/1Tmm2GvXN-9Uo8grPoXuJoPQM2JYPeSCf8a16RkJmFkA/\">here</a>.
Although, students can pick a project of their choice after discussing it with the professor."



course_policies: "This course will be run under the \"reasonable adults\" policy wherein it is assumed that all
students are reasonable adults that want to benefit the most of the course by attending the course regularly,
completing the homework assignments and projects on time, asking questions during the course and if they run
into problems, and checking back with the instructor and the TA (if there exists one) regularly to ensure good progress. <br/>

A more verbose version of the policy is available on <a href=\"https://spaf.cerias.purdue.edu/cpolicy.html\">Spaf's</a> page.
This course follows the policies listed on that page. If you have any question about the course policy,
don't hesitate to ask the instructor or the TA. <br/>

As a short summary: (i) you are expected to attend all classes (modulo good reasons),
(ii) you are supposed to hand in all work before the deadlines (there's a 10% point reduction per day for late hand-ins),
(iii) if you need special treatment or have special circumstances, talk to the instructor or TA (if there exists one). - Copied from Prof.Payers course."

course_semester: "Spring 2024"

nondiscrimination_statement: "Purdue University is committed to maintaining a community which recognizes and
values the inherent worth and dignity of every person; fosters tolerance, sensitivity, understanding, and
mutual respect among its members; and encourages each individual to strive to reach his or her own potential.
In pursuit of its goal of academic excellence, the University seeks to develop and nurture diversity.
The University believes that diversity among its many members strengthens the institution, stimulates creativity,
promotes the exchange of ideas, and enriches campus life. <a href=\"https://www.purdue.edu/purdue/ea_eou_statement.php\">Link to Purdue’s nondiscrimination policy statement</a>."

student_disability: "Purdue University strives to make learning experiences as accessible as possible.
If you anticipate or experience physical or academic barriers based on disability, you are welcome to let me know so that we can discuss options.
You are also encouraged to contact the Disability Resource Center at: drc@purdue.edu or by phone: 765-494-1247"

emergency_preparation: "In the event of a major campus emergency, course requirements, deadlines and grading
percentages are subject to changes that may be necessitated by a revised semester calendar or other circumstances
beyond the instructor’s control. Relevant changes to this course will be posted onto the course website or can be
obtained by contacting the instructors or TAs via email or phone. You are expected to read your @purdue.edu email on a frequent basis."

mental_health: "
It is important to make sure that you maintain your mental health.
<ul>
<li>If you find yourself beginning to feel some stress, anxiety and/or feeling slightly overwhelmed, try WellTrack.
Sign in and find information and tools at your fingertips, available to you at any time. </li>
<li> If you need support and information about options and resources, please see the Office of the Dean of Students for drop-in hours (M-F, 8 am- 5 pm). </li>
<li> If you’re struggling and need mental health services: Purdue University is committed to advancing the mental health
 and well-being of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of mental health support,
 services are available.
 For help, such individuals should contact Counseling and Psychological Services (CAPS) at 765-494-6995 during and
 after hours, on weekends and holidays, or by going to the CAPS office of the second floor of the Purdue University
 Student Health Center (PUSH) during business hours.</li>
 <li>TaskHuman offers private, real-time, on-demand, 1-on-1 video calls with wellness coaches covering over 800+ topics
 such as anxiety, mindfulness, reducing stress, clean eating, time management, in-home workouts, relationship tensions,
 financial issues, spiritual guidance and many more. You can access these wellness coaches from around the world 24/7.
 The College of Engineering has an exclusive agreement with TaskHuman which gives you FREE and UNLIMITED access to
 these resources. Over 3,200 calls have been made by College of Engineering students, staff, and faculty so far with an
  average satisfaction rating of 4.89/5.
  Learn more here: https://engineering.purdue.edu/ECE/TaskHuman.</li>
 </ul>"


baseurl: "/WiNets" # the subpath of your site, e.g. /blog/
url: "http://keerthidasala.github.io/" # the base hostname & protocol for your site

schoolname: "Purdue University"
schoolurl: "https://engineering.purdue.edu/ECE"

address: |
    Elmore Family School of Electrical and Computer Engineering
    Purdue University
    West Lafayette, IN, USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: UA-93239312-1

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    lecschedule:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
