# Site settings
course_name: Holistic Software Security
course_description: "The goal of the course is to bootstrap you into software security research. The
course provides a complete overview of different aspects of software security and
standard techniques used to solve various software security problems. We discuss
generic techniques such as Data flow analysis/ type inference/ dynamic analysis
that are also needed to perform research in other areas such as Software engineering
and program analysis."
course_semester: "Fall 2021"

baseurl: "/hss" # the subpath of your site, e.g. /blog/
url: "http://purs3lab.github.io/" # the base hostname & protocol for your site

schoolname: "Purdue University"
schoolurl: "https://engineering.purdue.edu/ECE"
twitter_username: machiry_msidc

address: |
    Electrical and Computer Engineering
    Purdue University
    West Lafayette, IN, USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: UA-93239312-1

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
